--- #YAML:1.0
name:               Net-SenderBase
version:            1.02
abstract:           Query the senderbase service
author:
    - Matt Sergeant <matt@sergeant.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Euclid:  0
    Net::DNS:        0.23
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
